import turtle

screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('pink')
t = turtle.Turtle()
t.penup()
t.goto(0,100)
t.pendown()
t.write("Things About Me", font=("Arial", 40, "bold italic"), align="center")

t.penup()
t.goto(0,-50)
t.pendown()
screen.addshape('me.gif')
t.shape('me.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-200,-200)
t.pendown()
screen.addshape('snow.gif')
t.shape('snow.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-200)
t.pendown()
screen.addshape('school.gif')
t.shape('school.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,200)
t.fillcolor('red')
t.begin_fill()
t.pendown()
t.speed(0)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
t.penup()

t.penup()
t.goto(0,200)
t.pendown()
t.write("Press Enter to Continue", font=("Arial", 20, "bold italic"), align="center")

round = input("Press Enter to Continue: ")
screen.bgcolor('lightblue')
t.clear()

t.penup()
t.goto(0,100)
t.pendown()
t.write("Favorite Food", font=("Arial", 40, "bold italic"), align="center")

t.penup()
t.goto(0,40)
t.pendown()
t.write("Samosa", font=("Arial", 20, "bold italic"), align="center")

t.penup()
t.goto(-200,40)
t.pendown()
t.write("Griled Cheese", font=("Arial", 20, "bold italic"), align="center")

t.penup()
t.goto(200,40)
t.pendown()
t.write("Noodle Soup", font=("Arial", 20, "bold italic"), align="center")

t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape('foodI.gif')
t.shape('foodI.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-200,-100)
t.pendown()
screen.addshape('foodII.gif')
t.shape('foodII.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-100)
t.pendown()
screen.addshape('foodIII.gif')
t.shape('foodIII.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,200)
t.pendown()
t.fillcolor('blue')
t.begin_fill()
t.setheading(0)
t.circle(50)
t.end_fill()
t.penup()

t.penup()
t.goto(0,200)
t.pendown()
t.write("Press Enter to Continue", font=("Arial", 20, "bold italic"), align="center")

round = input("Press Enter to Continue: ")
screen.bgcolor('lightyellow')
t.clear()

t.penup()
t.goto(0,100)
t.pendown()
t.write("Hobbies", font=("Arial", 40, "bold italic"), align="center")

t.penup()
t.goto(-200,40)
t.pendown()
t.write("Reading", font=("Arial", 15, "bold italic"), align="center")

t.penup()
t.goto(-100,40)
t.pendown()
t.write("Writing", font=("Arial", 15, "bold italic"), align="center")

t.penup()
t.goto(100,40)
t.pendown()
t.write("Drawing", font=("Arial", 15, "bold italic"), align="center")

t.penup()
t.goto(200,40)
t.pendown()
t.write("Games", font=("Arial", 15, "bold italic"), align="center")

t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape('pk2.gif')
t.shape('pk2.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-100)
t.pendown()
screen.addshape('cjredwine.gif')
t.shape('cjredwine.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-200,-100)
t.pendown()
screen.addshape('dtielephant.gif')
t.shape('dtielephant.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,200)
t.pendown()
t.fillcolor('purple')
t.begin_fill()
t.goto(300,200)
t.goto(250,275)
t.goto(200,200)
t.end_fill()
t.penup()

t.penup()
t.goto(0,200)
t.pendown()
t.write("Press Enter to Continue", font=("Arial", 20, "bold italic"), align="center")

round = input("Press Enter to Continue: ")
screen.bgcolor('azure')
t.clear()

t.penup()
t.goto(0,100)
t.pendown()
t.write("Favorite Movie", font=("Arial", 40, "bold italic"), align="center")

t.penup()
t.goto(0,40)
t.pendown()
t.write("Penguins of Madagascar", font=("Arial", 20, "bold italic"), align="center")

t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape('penguins.gif')
t.shape('penguins.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-100)
t.pendown()
screen.addshape('smallpenguin.gif')
t.shape('smallpenguin.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-10,-300)
t.fillcolor('yellow')
t.begin_fill()
t.pendown()
t.speed(0)
t.forward(150)
t.left(90)
t.forward(100)
t.left(90)
t.forward(150)
t.left(90)
t.forward(100)
t.end_fill()


t.penup()
t.goto(0,200)
t.pendown()
t.write("Press Enter to Continue", font=("Arial", 20, "bold italic"), align="center")

round = input("Press Enter to Continue: ")
screen.bgcolor('khaki')
t.clear()

t.penup()
t.goto(0,100)
t.pendown()
t.write("Favorite Sport", font=("Arial", 40, "bold italic"), align="center")

t.penup()
t.goto(0,40)
t.pendown()
t.write("Badminton", font=("Arial", 20, "bold italic"), align="center")

t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape('racket.gif')
t.shape('racket.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-100)
t.pendown()
screen.addshape('wikihow.gif')
t.shape('wikihow.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(0,-300)
t.setheading(135)
t.fillcolor('green')
t.begin_fill()
t.pendown()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()



t.penup()
t.goto(0,200)
t.pendown()
t.write("That's everything!", font=("Arial", 30, "bold italic"), align="center")



turtle.done()